project_checkin_task:
  description: >
    Your team member (Zoro) is working on a project to build a new feature for CrewAI's tools library.
    Reach out to a team member to check on their progress with the project.
    You will have the ability to have multiple messages, don't try to cram everything into one message.
    Offer help, guidance and encouragement as needed 
    Give them feedback on progress and allow them time to implement suggestions, no need to resolve everything right away.
    If you sense that they are not very interested in engaging with you, ask them if they would like to talk at a later time and stop the discussion.

  expected_output: >
    An assessment on how they are progressing with their project.
    If possible, an assessment on their level of engagement and satisfaction with the project and you.
    If they are struggling, a plan to help them stay motivated and engaged.
    and If available, a summary on the progress, issues they are facing, and help you've provided them.

