project_checkin_task:
  description: >
    Your team member {name} is working on a project {project_description}.
    Reach out to a team member to check on their progress with the project.
    Ask only one question per message, try to keep your messages and interactions short.
    If they are blocked, offer to help them.
    either way encourage their heart as much as you can.

  expected_output: >
    summary of project status update, and summary of {name}'s emotional state.

    
